steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg',
           'img_version=${_IMG_VERSION_1}',
           '-t',
           'gcr.io/$PROJECT_ID/cost-app-${_IMG_VERSION_1}',
           '.']
  substitutions:
      _IMG_VERSION_1: v1 # default value
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cost-app-${_IMG_VERSION_1}']
  images: ['gcr.io/$PROJECT_ID/cost-app-${_IMG_VERSION_1}']