steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cost-app:v1', '.']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cost-app:v1']
# Deploy image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/cost-app:v1', 'gcr.io/$PROJECT_ID/cost-app:latest']
images:
- gcr.io/$PROJECT_ID/cost-app:v1